import type { BattleCard, CardPosition } from '@/battle/types';

export const createMockMatch = (): BattleCard[] => [
  {
    id: 'opponent-pidgeot',
    name: 'Pidgeot ex',
    subtitle: 'Blustery Wind',
    category: 'creature',
    element: 'stone',
    symbol: '➤',
    hp: 280,
    damage: 0,
    attack: 'Scattering Wind',
    attackDamage: 120,
    ruleText: 'A cutting wind clears the field in a single sweep.',
    zone: 'opponent-active',
    slot: 0,
  },
  {
    id: 'radiant-charizard',
    name: 'Radiant Charizard',
    subtitle: 'Excited Heart',
    category: 'creature',
    element: 'flame',
    symbol: '✦',
    hp: 250,
    damage: 0,
    attack: 'Explosive Vortex',
    attackDamage: 250,
    ruleText: 'Its fiery aura builds as the battle reaches its end.',
    zone: 'opponent-bench',
    slot: 0,
  },
  {
    id: 'opponent-noctowl',
    name: 'Noctowl',
    subtitle: 'Night Watch',
    category: 'creature',
    element: 'grove',
    symbol: '◉',
    hp: 100,
    damage: 0,
    attack: 'Wing Beat',
    attackDamage: 30,
    ruleText: 'It keeps watch until the first light of dawn.',
    zone: 'opponent-bench',
    slot: 1,
  },
  {
    id: 'growlithe-active',
    name: 'Growlithe',
    subtitle: 'Puppy Pokémon',
    category: 'creature',
    element: 'flame',
    symbol: '♨',
    hp: 90,
    damage: 0,
    attack: 'Combustion',
    attackDamage: 30,
    ruleText: 'A loyal Fire-type that protects its friends.',
    zone: 'local-active',
    slot: 0,
    energyAttached: 1,
  },
  {
    id: 'arcanine-ex',
    name: 'Arcanine ex',
    subtitle: 'Legendary Pokémon',
    category: 'creature',
    element: 'flame',
    symbol: '♨',
    hp: 280,
    damage: 0,
    attack: 'Bright Flame',
    attackDamage: 250,
    ruleText: 'A blazing charge that leaves the whole arena alight.',
    zone: 'local-bench',
    slot: 0,
    energyAttached: 2,
    toolAttached: true,
  },
  {
    id: 'growlithe-bench',
    name: 'Growlithe',
    subtitle: 'Loyal Companion',
    category: 'creature',
    element: 'flame',
    symbol: '♨',
    hp: 90,
    damage: 0,
    attack: 'Combustion',
    attackDamage: 30,
    ruleText: 'The warmth of its flame keeps the team moving.',
    zone: 'local-bench',
    slot: 1,
  },
  {
    id: 'magma-basin',
    name: 'Magma Basin',
    subtitle: 'Stadium',
    category: 'trainer',
    cardType: 'stadium',
    element: 'flame',
    symbol: '⌁',
    ruleText:
      'A Fire Energy rises from the discard pile and warms a benched Pokémon.',
    zone: 'stadium',
    slot: 0,
  },
  {
    id: 'hand-arven',
    name: 'Arven',
    subtitle: 'Supporter',
    category: 'trainer',
    cardType: 'supporter',
    element: 'neutral',
    symbol: '⌖',
    ruleText: 'Search your deck for an Item and a Pokémon Tool.',
    zone: 'hand',
    slot: 0,
  },
  {
    id: 'hand-fire-energy',
    name: 'Fire Energy',
    subtitle: 'Basic Energy',
    category: 'energy',
    cardType: 'basic-energy',
    element: 'flame',
    symbol: '✦',
    ruleText: 'Provides one unit of Fire Energy.',
    zone: 'hand',
    slot: 1,
  },
  {
    id: 'hand-defiance-band',
    name: 'Defiance Band',
    subtitle: 'Pokémon Tool',
    category: 'trainer',
    cardType: 'tool',
    element: 'neutral',
    symbol: '◇',
    ruleText: 'A determined Pokémon can turn the tide of battle.',
    zone: 'hand',
    slot: 2,
  },
  {
    id: 'hand-growlithe',
    name: 'Growlithe',
    subtitle: 'Puppy Pokémon',
    category: 'creature',
    element: 'flame',
    symbol: '♨',
    hp: 90,
    damage: 0,
    attack: 'Combustion',
    attackDamage: 30,
    ruleText: 'Its warm coat stores heat for a quick burst of speed.',
    zone: 'hand',
    slot: 3,
  },
];

const positionByZone: Record<string, CardPosition> = {
  'opponent-active': { x: 50, y: 35, scale: 0.91, rotation: -1 },
  'opponent-bench-0': { x: 42, y: 23, scale: 0.66, rotation: -6 },
  'opponent-bench-1': { x: 58, y: 23, scale: 0.66, rotation: 5 },
  'local-active': { x: 50, y: 62, scale: 1, rotation: 0 },
  'local-bench-0': { x: 41, y: 51, scale: 0.68, rotation: -5 },
  'local-bench-1': { x: 59, y: 51, scale: 0.68, rotation: 5 },
  'local-bench-2': { x: 33, y: 51, scale: 0.66, rotation: -8 },
  'local-bench-3': { x: 67, y: 51, scale: 0.66, rotation: 8 },
  'local-bench-4': { x: 50, y: 49, scale: 0.65, rotation: 0 },
  stadium: { x: 31, y: 43, scale: 0.69, rotation: -4 },
  'knocked-out': { x: 50, y: 35, scale: 0.91, rotation: -1 },
  discard: { x: 50, y: 50, scale: 0, rotation: 0 },
};

export function getCardPosition(
  card: BattleCard,
  cards: BattleCard[],
): CardPosition {
  if (card.zone === 'hand') {
    const hand = cards
      .filter((candidate) => candidate.zone === 'hand')
      .sort((a, b) => a.slot - b.slot);
    const index = hand.findIndex((candidate) => candidate.id === card.id);
    const spread = Math.min(11.2, 58 / Math.max(hand.length - 1, 1));
    const centered = index - (hand.length - 1) / 2;
    return {
      x: 50 + centered * spread,
      y: 78.2 - Math.abs(centered) * 0.42,
      scale: 0.88,
      rotation: centered * 1.15,
    };
  }

  const key =
    card.zone === 'opponent-bench' || card.zone === 'local-bench'
      ? `${card.zone}-${card.slot}`
      : card.zone;
  return positionByZone[key] ?? { x: 50, y: 50, scale: 0.8, rotation: 0 };
}

export const initialDeckCount = 34;
export const initialPrizeCount = 6;

export const arvenSearchCards: BattleCard[] = [
  {
    id: 'search-escape-rope',
    name: 'Escape Rope',
    subtitle: 'Item',
    category: 'trainer',
    cardType: 'item',
    element: 'neutral',
    symbol: '↗',
    ruleText: 'Both players switch their Active Pokémon.',
    zone: 'deck',
    slot: 0,
  },
  {
    id: 'search-defiance-band',
    name: 'Defiance Band',
    subtitle: 'Pokémon Tool',
    category: 'trainer',
    cardType: 'tool',
    element: 'neutral',
    symbol: '◇',
    ruleText: 'A determined Pokémon can turn the tide of battle.',
    zone: 'deck',
    slot: 0,
  },
  {
    id: 'search-vitality-charm',
    name: 'Vitality Charm',
    subtitle: 'Pokémon Tool',
    category: 'trainer',
    cardType: 'tool',
    element: 'grove',
    symbol: '❋',
    ruleText: "A small charm that steadies a Pokémon's resolve.",
    zone: 'deck',
    slot: 0,
  },
];

export const raihanSearchCards: BattleCard[] = [
  {
    id: 'raihan-search-fire-energy',
    name: 'Fire Energy',
    subtitle: 'Basic Energy',
    category: 'energy',
    cardType: 'basic-energy',
    element: 'flame',
    symbol: '✦',
    ruleText: "A basic Fire Energy from the opponent's deck.",
    zone: 'deck',
    slot: 0,
  },
  {
    id: 'raihan-search-switch-cart',
    name: 'Switch Cart',
    subtitle: 'Item',
    category: 'trainer',
    cardType: 'item',
    element: 'neutral',
    symbol: '↗',
    ruleText: 'A quick route between the Active Spot and the Bench.',
    zone: 'deck',
    slot: 0,
  },
  {
    id: 'raihan-search-pokemon',
    name: 'Arcanine ex',
    subtitle: 'Pokémon',
    category: 'creature',
    element: 'flame',
    symbol: '♨',
    hp: 280,
    damage: 0,
    attack: 'Bright Flame',
    attackDamage: 250,
    ruleText: "A Pokémon revealed from the opponent's deck.",
    zone: 'deck',
    slot: 0,
  },
];
